'use client'

import Link from "next/link"
import Image from "next/image"
import { ArrowRight, Bot, CalendarDays, CheckCircle2, Mail, Menu, Sparkles, Target, X } from "lucide-react"
import { useState } from "react"

const features = [
  { icon: Bot, title: "Friendly AI coach", text: "Ask questions, rehearse client conversations, and get practical guidance anytime." },
  { icon: CalendarDays, title: "Calendar practice", text: "Watch a guided demo, then schedule a real-world meeting in a timed simulation." },
  { icon: Mail, title: "Inbox practice", text: "Learn to triage, reply, and follow up with confidence in a safe mock inbox." },
]

export function LandingPage() {
  const [open, setOpen] = useState(false)
  return <main className="landing min-h-dvh bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/90 backdrop-blur-xl">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8" aria-label="Main navigation">
        <Link href="/" className="flex items-center gap-3"><Image src="/imputik-logo.png" alt="IMPUTIK AI" width={42} height={42} className="size-10 rounded-xl object-cover" /><span className="text-lg font-extrabold tracking-tight">Imputik<span className="text-accent">AI</span></span></Link>
        <div className="hidden items-center gap-7 text-sm font-semibold text-muted-foreground md:flex"><a href="#about">About</a><a href="#practice">Practice</a><a href="#how">How it works</a></div>
        <Link href="/app" className="hidden items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-neon md:flex">Start learning <ArrowRight size={16} /></Link>
        <button className="rounded-lg border border-border p-2 md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button>
      </nav>
      {open && <div className="flex flex-col gap-4 border-t border-border px-5 py-5 md:hidden"><a href="#about" onClick={() => setOpen(false)}>About</a><a href="#practice" onClick={() => setOpen(false)}>Practice</a><Link href="/app" className="rounded-xl bg-primary px-4 py-3 text-center font-bold text-primary-foreground">Start learning</Link></div>}
    </header>

    <section className="mx-auto flex max-w-7xl flex-col items-center gap-10 px-5 py-16 lg:flex-row lg:px-8 lg:py-24">
      <div className="flex-1 text-center lg:text-left"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-accent/40 bg-accent/10 px-4 py-2 text-xs font-bold text-accent"><Sparkles size={15} /> Built for aspiring virtual assistants</div><h1 className="text-balance text-4xl font-black leading-tight tracking-tight sm:text-6xl">Practice the work.<br/><span className="text-accent">Build the confidence.</span></h1><p className="mx-auto mt-6 max-w-xl text-pretty text-base leading-relaxed text-muted-foreground lg:mx-0 lg:text-lg">IMPUTIK AI turns VA training into hands-on sessions. Learn from short demos, complete realistic client tasks, and talk with a coach who is always in your corner.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row lg:justify-start"><Link href="/app" className="flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-4 font-extrabold text-primary-foreground shadow-neon">Enter the learning hub <ArrowRight size={18}/></Link><a href="#practice" className="rounded-xl border border-border bg-card px-6 py-4 text-center font-bold">See practice sessions</a></div><div className="mt-7 flex flex-wrap justify-center gap-5 text-xs text-muted-foreground lg:justify-start"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-accent"/> Free to use</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-accent"/> No account required</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-accent"/> Open source</span></div></div>
      <div className="relative flex w-full flex-1 justify-center"><div className="absolute inset-10 rounded-full bg-primary/20 blur-3xl"/><div className="relative w-full max-w-lg rounded-3xl border border-border bg-card/80 p-4 shadow-2xl"><Image src="/imputik-logo.png" alt="IMPUTIK AI virtual assistant coach logo" width={1024} height={1024} priority className="aspect-square w-full rounded-2xl object-cover"/></div></div>
    </section>

    <section id="about" className="border-y border-border bg-card/40"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="mx-auto max-w-2xl text-center"><span className="text-xs font-extrabold uppercase tracking-widest text-accent">A better way to train</span><h2 className="mt-3 text-balance text-3xl font-black sm:text-4xl">Your virtual hub for job-ready VA skills</h2><p className="mt-4 leading-relaxed text-muted-foreground">Move beyond passive videos with guided practice, instant feedback, and coaching designed around actual client work.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{features.map(({icon:Icon,title,text}) => <article key={title} className="rounded-2xl border border-border bg-card p-6"><div className="mb-5 flex size-12 items-center justify-center rounded-xl bg-primary/15 text-accent"><Icon size={24}/></div><h3 className="text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>

    <section id="practice" className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid items-center gap-10 lg:grid-cols-2"><div><span className="text-xs font-extrabold uppercase tracking-widest text-accent">Demo, practice, assess</span><h2 className="mt-3 text-balance text-3xl font-black sm:text-4xl">Learn by doing the tasks clients actually need</h2><p className="mt-4 leading-relaxed text-muted-foreground">Every practice lab starts with a clear walkthrough. When you are ready, enter assessment mode, work against the clock, and receive a score with specific feedback.</p><div className="mt-7 flex flex-col gap-4">{["Watch the coach demonstrate a professional workflow","Try the task with hints and a realistic workspace","Complete a timed assessment and improve your best score"].map((t,i)=><div key={t} className="flex gap-4"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-accent font-mono text-sm font-bold text-accent-foreground">{i+1}</span><p className="pt-1 text-sm font-semibold">{t}</p></div>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-border bg-card p-6"><CalendarDays className="text-accent" size={32}/><h3 className="mt-6 text-xl font-extrabold">Calendar management</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Resolve conflicts, schedule across time zones, and add clear agendas.</p></div><div className="rounded-3xl border border-border bg-card p-6 sm:mt-8"><Mail className="text-primary" size={32}/><h3 className="mt-6 text-xl font-extrabold">Email management</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Prioritize messages, draft polished replies, and choose the right next action.</p></div></div></div></section>

    <section id="how" className="mx-5 mb-12 rounded-3xl border border-primary/30 bg-card px-6 py-14 text-center shadow-neon lg:mx-auto lg:max-w-7xl"><Target className="mx-auto text-accent" size={36}/><h2 className="mx-auto mt-5 max-w-2xl text-balance text-3xl font-black">Ready to become the VA clients trust?</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Start with the guided 20-day learning path, then prove your skills in the Practice Lab.</p><Link href="/app" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-4 font-extrabold text-primary-foreground">Open IMPUTIK AI <ArrowRight size={18}/></Link></section>
    <footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 py-8 text-sm text-muted-foreground sm:flex-row lg:px-8"><span className="font-bold text-foreground">IMPUTIK AI</span><span>Free, open-source VA career training.</span><a href="https://github.com" target="_blank" rel="noreferrer">MIT licensed</a></div></footer>
  </main>
}
