'use client'

import { useEffect, useState } from "react"
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, Mail, Play, RotateCcw, Send, Sparkles } from "lucide-react"

type Module = "calendar" | "email"
type Mode = "menu" | "demo" | "assessment" | "result"
type Result = { module: Module; score: number; feedback: string[]; date: string }
const RESULTS_KEY = "imputik-practice-results"

export function PracticeLab() {
  const [module, setModule] = useState<Module>("calendar")
  const [mode, setMode] = useState<Mode>("menu")
  const [seconds, setSeconds] = useState(300)
  const [calendar, setCalendar] = useState({ date: "2026-07-16", time: "14:00", duration: "30", title: "Project kickoff", agenda: "" })
  const [email, setEmail] = useState({ priority: "", subject: "Re: Friday deliverables", body: "" })
  const [result, setResult] = useState<Result | null>(null)
  const [best, setBest] = useState<Record<string, number>>({})

  useEffect(() => { try { const values: Result[] = JSON.parse(localStorage.getItem(RESULTS_KEY) || "[]"); setBest(values.reduce((a,r)=>({...a,[r.module]:Math.max(a[r.module]||0,r.score)}),{} as Record<string,number>)) } catch {} }, [])
  useEffect(() => { if (mode !== "assessment" || seconds <= 0) return; const id = window.setInterval(()=>setSeconds(s=>s-1),1000); return ()=>clearInterval(id) }, [mode, seconds])
  useEffect(() => { if (mode === "assessment" && seconds === 0) grade() }, [seconds, mode])

  function start(nextModule: Module, nextMode: Mode) { setModule(nextModule); setSeconds(nextModule === "calendar" ? 300 : 360); setCalendar({ date: "2026-07-16", time: "14:00", duration: "30", title: "Project kickoff", agenda: "" }); setEmail({ priority: "", subject: "Re: Friday deliverables", body: "" }); setMode(nextMode) }
  function grade() {
    let score = 0; const feedback:string[] = []
    if (module === "calendar") {
      if (calendar.date === "2026-07-17") score += 25; else feedback.push("Choose Friday, July 17 as requested.")
      if (calendar.time === "15:00") score += 25; else feedback.push("Convert 10:00 AM New York to 3:00 PM London.")
      if (calendar.duration === "45") score += 15; else feedback.push("Set the requested 45-minute duration.")
      if (calendar.title.toLowerCase().includes("acme") && calendar.title.toLowerCase().includes("kickoff")) score += 15; else feedback.push("Use a specific title with the client and purpose.")
      if (calendar.agenda.trim().length >= 30) score += 20; else feedback.push("Add a useful agenda with outcomes or preparation notes.")
    } else {
      if (email.priority === "high") score += 20; else feedback.push("Treat a deadline-risk message as high priority.")
      if (email.subject.toLowerCase().includes("friday") && email.subject.toLowerCase().includes("deliverable")) score += 15; else feedback.push("Keep the subject specific to Friday deliverables.")
      const body = email.body.toLowerCase()
      if (body.includes("sorry") || body.includes("apolog")) score += 15; else feedback.push("Acknowledge the delay professionally.")
      if (body.includes("thursday") || body.includes("tomorrow")) score += 20; else feedback.push("Confirm the draft will be sent by Thursday.")
      if (body.includes("friday")) score += 15; else feedback.push("Reassure the client that Friday remains on track.")
      if (email.body.trim().length >= 80) score += 15; else feedback.push("Write a complete but concise client response.")
    }
    if (feedback.length === 0) feedback.push("Excellent work. You completed every requirement clearly and professionally.")
    const next = { module, score, feedback, date: new Date().toISOString() }; setResult(next); setBest(b=>({...b,[module]:Math.max(b[module]||0,score)})); try { const old=JSON.parse(localStorage.getItem(RESULTS_KEY)||"[]"); localStorage.setItem(RESULTS_KEY,JSON.stringify([next,...old].slice(0,20))) } catch {}; setMode("result")
  }

  if (mode === "menu") return <section className="flex flex-col gap-6"><div><span className="eyebrow">Practice lab</span><h2 className="mt-2 text-3xl font-black">Turn lessons into real skills</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Start with a guided walkthrough, then complete the assessment in a realistic workspace. Your best scores stay on this device.</p></div><div className="grid gap-4 lg:grid-cols-2">{([{id:"calendar",icon:CalendarDays,title:"Calendar management",desc:"Schedule a cross-time-zone kickoff without missing a client requirement.",time:"5 min"},{id:"email",icon:Mail,title:"Email management",desc:"Triage a deadline risk and send a professional, reassuring response.",time:"6 min"}] as const).map(item=><article key={item.id} className="practice-card"><div className="flex items-start justify-between"><div className="icon-tile"><item.icon size={24}/></div>{best[item.id] !== undefined && <span className="score-chip">Best {best[item.id]}%</span>}</div><h3 className="mt-5 text-xl font-extrabold">{item.title}</h3><p className="mt-2 min-h-12 text-sm leading-relaxed text-muted-foreground">{item.desc}</p><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><Clock3 size={14}/>{item.time} assessment</div><div className="mt-5 flex gap-2"><button className="secondary-action flex-1" onClick={()=>start(item.id,"demo")}><Play size={16}/> Watch demo</button><button className="primary-action flex-1" onClick={()=>start(item.id,"assessment")}>Start assessment</button></div></article>)}</div></section>

  if (mode === "result" && result) return <section className="mx-auto max-w-2xl"><button className="back-link" onClick={()=>setMode("menu")}><ArrowLeft size={16}/> Practice lab</button><div className="result-card"><div className="mx-auto flex size-16 items-center justify-center rounded-2xl bg-primary/20 text-accent"><CheckCircle2 size={34}/></div><span className="mt-5 text-sm font-bold uppercase tracking-widest text-muted-foreground">Assessment complete</span><div className="mt-2 text-6xl font-black text-accent">{result.score}%</div><h2 className="mt-3 text-2xl font-black">{result.score >= 80 ? "Client-ready work" : result.score >= 60 ? "Good foundation" : "Keep practicing"}</h2><div className="mt-7 flex flex-col gap-3 text-left">{result.feedback.map(text=><div key={text} className="feedback-row"><Sparkles size={17}/><span>{text}</span></div>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button className="secondary-action flex-1" onClick={()=>setMode("demo")}><Play size={16}/> Review demo</button><button className="primary-action flex-1" onClick={()=>start(module,"assessment")}><RotateCcw size={16}/> Try again</button></div></div></section>

  return <section className="mx-auto max-w-5xl"><div className="mb-5 flex items-center justify-between gap-4"><button className="back-link" onClick={()=>setMode("menu")}><ArrowLeft size={16}/> Practice lab</button>{mode === "assessment" && <span className={`timer ${seconds < 60 ? "timer-danger" : ""}`}><Clock3 size={16}/>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</span>}</div>{mode === "demo" ? <Demo module={module} onReady={()=>start(module,"assessment")}/> : <div className="grid gap-5 lg:grid-cols-[.85fr_1.4fr]"><Brief module={module}/>{module === "calendar" ? <CalendarWorkspace value={calendar} setValue={setCalendar}/> : <EmailWorkspace value={email} setValue={setEmail}/>}<div className="lg:col-start-2"><button className="primary-action w-full" onClick={grade}><Send size={16}/> Submit assessment</button></div></div>}</section>
}

function Brief({module}:{module:Module}) { return <aside className="brief-card"><span className="eyebrow">Client brief</span><h3 className="mt-3 text-xl font-extrabold">{module === "calendar" ? "Schedule the Acme kickoff" : "Respond to a delivery risk"}</h3>{module === "calendar" ? <div className="brief-message">“Please schedule our Acme kickoff for Friday, July 17 at 10:00 AM New York time. I’ll be in London. Make it 45 minutes and include an agenda covering goals, owners, and next steps.”</div> : <div className="brief-message">“Our Friday deliverables may be delayed because research is taking longer. Reply to Maya, apologize, promise the draft by Thursday, and reassure her Friday is still on track.”</div>}<p className="mt-4 text-xs leading-relaxed text-muted-foreground">Review every requirement before submitting. Clear details and professional judgment both count toward your score.</p></aside> }
function Demo({module,onReady}:{module:Module;onReady:()=>void}) { const steps=module === "calendar" ? ["Extract date, source time zone, duration, and agenda requirements.","Convert 10:00 AM New York to 3:00 PM London for July.","Use a specific event title and add an outcome-focused agenda.","Review all details before sending the invitation."] : ["Mark the deadline-risk email as high priority.","Acknowledge the delay without over-explaining or blaming.","Commit to a concrete Thursday draft and confirm Friday delivery.","Keep the reply concise, warm, and action-oriented."]; return <div className="demo-card"><span className="eyebrow">Guided demonstration</span><h2 className="mt-2 text-3xl font-black">{module === "calendar" ? "How to schedule like a pro" : "How to handle a deadline risk"}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Follow the coach&apos;s workflow before you enter the timed assessment.</p><div className="mt-7 flex flex-col gap-3">{steps.map((step,i)=><div className="demo-step" key={step}><span>{i+1}</span><p>{step}</p></div>)}</div><div className="coach-tip"><Sparkles size={20}/><p><strong>Coach tip:</strong> {module === "calendar" ? "Never assume the client’s time zone. Write both zones in your notes before scheduling." : "Clients value early visibility. Pair the problem with a clear next action and delivery date."}</p></div><button className="primary-action mt-7 w-full sm:w-auto" onClick={onReady}>I&apos;m ready for the assessment</button></div> }
function CalendarWorkspace({value,setValue}:{value:{date:string;time:string;duration:string;title:string;agenda:string};setValue:(v:any)=>void}) { return <div className="workspace"><div className="workspace-head"><CalendarDays/><div><b>New calendar event</b><span>All times shown in London</span></div></div><div className="form-grid"><label>Event title<input value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label>Date<input type="date" value={value.date} onChange={e=>setValue({...value,date:e.target.value})}/></label><label>Start time<input type="time" value={value.time} onChange={e=>setValue({...value,time:e.target.value})}/></label><label>Duration<select value={value.duration} onChange={e=>setValue({...value,duration:e.target.value})}><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option></select></label><label className="full-field">Agenda<textarea rows={6} placeholder="Add goals, owners, next steps, and preparation notes..." value={value.agenda} onChange={e=>setValue({...value,agenda:e.target.value})}/></label></div></div> }
function EmailWorkspace({value,setValue}:{value:{priority:string;subject:string;body:string};setValue:(v:any)=>void}) { return <div className="workspace"><div className="workspace-head"><Mail/><div><b>Reply to Maya Chen</b><span>maya@client.example</span></div></div><div className="form-grid"><label>Priority<select value={value.priority} onChange={e=>setValue({...value,priority:e.target.value})}><option value="">Choose priority</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Subject<input value={value.subject} onChange={e=>setValue({...value,subject:e.target.value})}/></label><label className="full-field">Message<textarea rows={10} placeholder="Hi Maya, ..." value={value.body} onChange={e=>setValue({...value,body:e.target.value})}/></label></div></div> }
